version: '2.1'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:1.9.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
            - storage-proxy

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:2.3.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - GATEWAY_IP
            - INTEGRATION_VERSION
            - MENDER_ARTIFACT_VERSION
            - MENDER_VERSION
            - MENDER_DEB_PACKAGE_VERSION

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:2.1.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:2.2.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
            - mender-conductor

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:1.7.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:1.10.0b1-build1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-workflows
    #
    mender-workflows-server:
        image: mendersoftware/workflows:1.0.0b1-build1
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-create-artifact-worker
    #
    mender-create-artifact-worker:
        image: mendersoftware/create-artifact-worker:1.0.0b1-build1
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        environment:
            - WORKFLOWS_MONGO_URL=mongodb://mongo-workflows:27017
            - CREATE_ARTIFACT_GATEWAY_URL=https://mender-api-gateway
            - CREATE_ARTIFACT_DEPLOYMENTS_URL=http://mender-deployments:8080
        networks:
            - mender
        depends_on:
            - mender-mongo

    mender-mongo:
        image: mongo:3.6
        extends:
            file: common.yml
            service: mender-base
        networks:
            mender:
                aliases:
                    - mongo-tenantadm
                    - mongo-deployments
                    - mongo-device-auth
                    - mongo-inventory
                    - mongo-useradm
                    - mongo-workflows

    mender-conductor:
        image: mendersoftware/mender-conductor:1.6.0b1-build1
        depends_on:
            - mender-elasticsearch
            - mender-redis
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

    mender-elasticsearch:
        image: elasticsearch:6.8.6
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - network.host=0.0.0.0

    mender-redis:
        image: redis:5-alpine3.8
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

networks:
    mender:
